default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: utf8
  username: postgres
  password: 123456
  host: 127.0.0.1
  port: 5432

development:
  <<: *default
  database: iqoptions

test:
  <<: *default
  database: iqoptions

production:
  <<: *default
  database: iqoptions
